[package]
name = "libcras"
version = "0.1.0"
authors = ["The Chromium OS Authors"]
edition = "2018"

[dependencies]
libc = "*"
cras-sys = { path = "../cras-sys" } # provided by ebuild
data_model = { path = "../../../../../platform/crosvm/data_model" } # provided by ebuild
