[package]
name = "cras_tests"
version = "0.1.0"
authors = ["The Chromium OS Authors"]
edition = "2018"

[dependencies]
libcras = { path = "../libcras" } # provided by ebuild
audio_streams = { path = "../../../audio_streams" } # provided by ebuild
